CREATE DATABASE db_exec2;

CREATE TABLE FUNCIONARIOS(
    id INT PRIMARY KEY ,
    name VARCHAR(20) NOT NULL,
    age SMALLINT NOT NULL,
    adress VARCHAR(40) NOT NULL,
    salary DECIMAL(18,2) NOT NULL
);


INSERT INTO FUNCIONARIOS VALUES (1,'Billy Butcher',40,'Centro',6300.67);
INSERT INTO FUNCIONARIOS VALUES (2,'Hughie Campbell',28,'Santo Agostinho',3050.10);
INSERT INTO FUNCIONARIOS VALUES (3, 'Annie January', 26, 'Santo Agostinho', 4450.35);
INSERT INTO FUNCIONARIOS VALUES (4, 'Susan Raynor', 34, 'Nossa Senhora Aparecida', 2500);
INSERT INTO FUNCIONARIOS VALUES (5, 'Alastair Adana', 43, 'Serra', 4700.50);
INSERT INTO FUNCIONARIOS VALUES (6, 'Stan Edigar', 45, 'Belvedere', 4701.50);
INSERT INTO FUNCIONARIOS VALUES (7, 'Kimiko Miyashiro', 31, 'Buritis', 1100.10);
INSERT INTO FUNCIONARIOS VALUES (8, 'Grace Mallory', 41, 'Lourdes', 8040);

SELECT 
    T1.NOME AS SALARIO_MENOR,
     T2.NOME AS SALARIO_MAIOR
FROM 
    FUNCIONARIOS T1
INNER JOIN 
    FUNCIONARIOS T2
ON 
    T1.SALARIO < T2.SALARIO
ORDER BY 
    T1.SALARIO, T2.SALARIO